### ISSUE TITLE
Develop table design

### ISSUE THREAD

**Issue by lukefretwell** [cagov/cwds#1]
Edit the default table design:

https://cwds.dev/docs/4.3/templates/quick-answer/

@artuoma after seeing it in the design system, I'm fine with Bootstrap default. 

I see you're using a striped version here, but I'd use default for everything until we see a need to modify: https://cwds.dev/docs/4.3/templates/quick-answer/

@lukefretwell I agree, perhaps if a table is really long or data is complex the striped style can be used

**Comment by abquirarte** [comment]
@artuoma - is this done? https://cwds.dev/docs/4.3/templates/quick-answer/

**Comment by artuoma** [comment]
@abquirarte Yes it is, can be found here but is more of a decision than a change anywhere:

https://cwds.dev/docs/4.3/templates/quick-answer/

- [ ] Confirmed

**Comment by abquirarte** [comment]
ok, thank you @artuoma !
