### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by lukefretwell** [cagov/cwds#15]
@aaronhans I think it's OK to use the exact homepage with these mods:

- [x] Change 'Bootstrap' to 'California Web Design System'
- [x] New description (I'll write-up and add here)
- [x] Remove `masthead-followup` section

**Comment by aaronhans** [comment]
I fixed the issues with the nav in the main branch and Luke modified the homepage

**Comment by KimberlyglennTSM** [comment]
Reviewed and Closed.
