### ISSUE TITLE
Deploy documentation browsable on github pages

### ISSUE THREAD

**Issue by aaronhans** [cagov/cwds#17]
Make sure the generated docs use our custom theme and are browsable both on local development environments and the deployed github pages, make sure the generated docs create files in folder compatible with github pages settings

**Comment by aaronhans** [comment]
cwds repository is now browseable on github pages, gohugo config is modified to use directories compatible with both local and gh pages url structure

**Comment by KimberlyglennTSM** [comment]
Reviewed and approved.
