### ISSUE TITLE
Create news + media list content templates

### ISSUE THREAD

**Issue by lukefretwell** [cagov/cwds#19]
- [x] set up 'news' repo to host content/tech (@aaronhans)
- [x] create /news page (for list of news items template)
- [x] create list of news items template (use card: https://cwds.dev/docs/4.3/components/card/ + template: https://cwds.dev/docs/4.3/templates/news/- @artuoma to updates)
- [x] post template (template: https://cwds.dev/docs/4.3/templates/news/ - @artuoma to update)
- [x] move Medium posts to repo
- [x] clean up CSS, move to main file (@artuoma @lukefretwell)
- [x] Add 'News' link to footer
- [x] Map DNS to news.alpha.ca.gov
- [x] create a done doing for this week
- [x] update header/footer wrapper
- [x] ensure fonts are included (currently displaying arial instead of public sans)

## Bugs

- [x] Links on [main news page](https://cagov.github.io/news/) returns page not found (they work if you add the /news before - note this all works fine on local) (@aaronhans)
- [x] news cards overlap on smaller screen size (@artuoma)

cc @jpetrucione

**Comment by lukefretwell** [comment]
FYI @artuoma I've done some work around this and will push to CWDS soon.

**Comment by abquirarte** [comment]
@lukefretwell how is this different from this issue: https://github.com/cagov/Alpha/issues/69

**Comment by lukefretwell** [comment]
@abquirarte up to you whether we want to merge. I was just using #69 as a means to establish what technology we'd use. The is for actually executing now that the @aaronhans has deployed it. So you can merge them or just close #69.

**Comment by abquirarte** [comment]
ok, closing 69. Thank you @lukefretwell

**Comment by lukefretwell** [comment]
## Progress

* News list: https://cagov.github.io/news/
* Blog post: https://cagov.github.io/news/alpha-ca-gov-product-framing/

## Bugs/additional items

Documented in above checklist

cc @aaronhans

**Comment by lukefretwell** [comment]
@aaronhans @artuoma @abquirarte @jpetrucione I've created a punch list of thoughts for future clean-up so anything we can't get into this sprint (as well as any other ideas or anything I missed) in the above checklist, feel free to add there:

https://github.com/cagov/news/issues/1

**Comment by lukefretwell** [comment]
@artuoma added checkboxes to bottom of list for header/footer and font. Also note the CSS issues.
