### ISSUE TITLE
Develop button designs

### ISSUE THREAD

**Issue by lukefretwell** [cagov/cwds#2]
@artuoma suggest just focusing on the following for now:

```
<button type="button" class="btn btn-primary">Primary</button>
<button type="button" class="btn btn-light">Light</button>
```

Colors:

* #000000 for dark color (including border)
* #ffffff for light

https://getbootstrap.com/docs/4.0/components/buttons/

@lukefretwell https://cwds.dev/docs/4.3/components/buttons/

**Comment by lukefretwell** [comment]
@artuoma see specs for button design ☝️ .

Note on this page the primary link button looks very different than the others. We need to code for the default and tweak the coloring for the primary. This way they all look the same (font style, size). Note you don't need to code for size as there's a class for that (https://cwds.dev/docs/4.3/components/buttons/#sizes). I'm fine with coding defaults to look different, but they just need to be the same for all of them (https://cwds.dev/docs/4.3/components/buttons/#button-tags).

Note: We should use the same treatment for form buttons.

**Comment by abquirarte** [comment]
@artuoma is this done? if so, can you point to where the final doc/product is?

**Comment by lukefretwell** [comment]
Done: https://cwds.dev/docs/4.3/components/buttons/
