### ISSUE TITLE
Review icon options

### ISSUE THREAD

**Issue by lukefretwell** [cagov/cwds#4]
* USWDS (https://designsystem.digital.gov/components/icons/)
* Font Awesome (https://fontawesome.com)
* 18F (https://brand.18f.gov/icons/)
* California state icons (http://beta.template.webstandards.ca.gov/sample/icon-fonts.html) via @artuoma

**Comment by artuoma** [comment]
Using the CA State Web Template icon font: https://beta.template.webstandards.ca.gov/sample/icon-fonts.html

This icon font has many custom designed icons that have been informed by other state entity needs and requests.

**Comment by lukefretwell** [comment]
@artuoma I'm fine with closing this issue given your comments. We should probably add a reference to this in the design system.
