### ISSUE TITLE
Add breadcrumb component?

### ISSUE THREAD

**Issue by lukefretwell** [cagov/cwds#6]
Note USWDS does not have a breadcrumb component, so we should discuss with folks there to understand why they've chosen not to support this design element at the moment.

Reference:

* https://medium.com/madison-ave-collective/are-breadcrumbs-still-fresh-for-ux-6e72b0f96e9b
* http://schema.org/BreadcrumbList

**Comment by artuoma** [comment]
I think we should do this. We can test this in some of the more complex user stories like Lifeline.

**Comment by lukefretwell** [comment]
@artuoma closing this as I think we've addressed for now.
